#!/usr/bin/env ruby
# The Awesome language!
# 
# usage:
#   ./awesome example.awm # to eval a file
#   ./awesome             # to start the REPL
#
# on Windows run with: ruby awesome [options]

$:.unshift "." # Fix for Ruby 1.9
require_relative '.\interpreter'
require "readline"

interpreter = Interpreter.new

# If a file is given we eval it.
if file = ARGV.first
  interpreter.interpret File.read(file)

# Start the REPL, read-eval-print-loop, or interactive interpreter
else
  puts "Ulysse's REPL, say 'quit' to exit"
  loop do
    line = Readline::readline(">> ")
    Readline::HISTORY.push(line)

    if line == "quit"
      puts "Bye!"
      exit
    end

    result = interpreter.interpret(line)
    puts "=> #{result.value.inspect}"
  end
end